#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Reproduce
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=/home/scur2868/IR2/vec2text/scripts/outputs/reproduce_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

source /home/scur2868/IR2/v2t-env/bin/activate
cd /home/scur2868/IR2/vec2text/

# model options:  jxm/gtr__nq__32__correct  or  jxm/vec2text__openai_ada002__msmarco__msl128__corrector
python reproduce.py --model jxm/vec2text__openai_ada002__msmarco__msl128__corrector --steps 50 --beam-width 8
