#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=ReproduceT2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=06:00:00
#SBATCH --output=/home/scur2868/IR2/vec2text/scripts/outputs/repro_T2_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

source /home/scur2868/IR2/v2t-env/bin/activate
cd /home/scur2868/IR2/vec2text

python reproduce_T2_private.py --max_samples 1000 > scripts/outputs/T2_gtr-50steps-8beam_bioasq_1ksamples.log