#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Reproduce
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=09:00:00
#SBATCH --output=/home/scur2845/vec2text/scripts/outputs/repro_T2_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

conda activate vec2text
cd /home/scur2845/vec2text/

# model options:  jxm/gtr__nq__32__correct  or  jxm/vec2text__openai_ada002__msmarco__msl128__corrector
# python reproduce.py --model jxm/gtr__nq__32__correct --steps 0 --beam-width 1 > scripts/outputs/repro_T1_gtr-0steps-1beam.log
# python reproduce_T2.py --model jxm/gtr__nq__32__correct --steps 1 --beam-width 1 --beir_dataset quora --max_samples 10000 > scripts/outputs/repro_T2_gtr-1steps-1beam.log
# python reproduce_T2.py --model jxm/gtr__nq__32__correct --steps 20 --beam-width 1 --beir_dataset quora --max_samples 1000 > scripts/outputs/repro_T2_gtr-20steps-1beam.log
# python reproduce_T2.py --model jxm/gtr__nq__32__correct --steps 50 --beam-width 1 --beir_dataset quora --max_samples 1000 > scripts/outputs/repro_T2_gtr-50steps-1beam.log
# python reproduce_T2.py --model jxm/gtr__nq__32__correct --steps 50 --beam-width 2 --beir_dataset quora --max_samples 1000 > scripts/outputs/repro_T2_gtr-50steps-2beam.log
# python reproduce_T2.py --model jxm/gtr__nq__32__correct --steps 50 --beam-width 4 --beir_dataset quora --max_samples 1000 > scripts/outputs/repro_T2_gtr-50steps-4beam.log
python reproduce_T2.py --model jxm/gtr__nq__32__correct --steps 50 --beam-width 8 --beir_dataset quora --max_samples 1000 > scripts/outputs/repro_T2_gtr-50steps-8beam.log
